//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocationAdmin
    {
        public int LocationID { get; set; }
        public Nullable<int> PersonID { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual Person Person { get; set; }
    }
}
