//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProgDatabaseEntities : DbContext
    {
        public ProgDatabaseEntities()
            : base("name=ProgDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Action> Actions { get; set; }
        public virtual DbSet<Decision> Decisions { get; set; }
        public virtual DbSet<DecisionLevel> DecisionLevels { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<LocationAdmin> LocationAdmins { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<Request> Requests { get; set; }
        public virtual DbSet<RequestType> RequestTypes { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
    }
}
