
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DB
{

using System;
    using System.Collections.Generic;
    
public partial class Decision
{

    public int DecisionID { get; set; }

    public int RequestID { get; set; }

    public int ApproverID { get; set; }

    public Nullable<System.DateTime> ChangeDate { get; set; }

    public int ActionID { get; set; }

    public string Reason { get; set; }

    public int DecisionLevelID { get; set; }



    public virtual Action Action { get; set; }

    public virtual DecisionLevel DecisionLevel { get; set; }

    public virtual Person Person { get; set; }

    public virtual Request Request { get; set; }

    public virtual Person Person1 { get; set; }

}

}
